export const dishesShowcase = [
    {
        id: 'dish_poulet',
        name: 'Poulet Bicyclette Braisé Kpédji',
        category: 'signature',
        price: 4500,
        currency: 'FCFA',
        rating: 4.9,
        reviewsCount: 142,
        prepTime: '20 min',
        image: '/images/poulet_braise_1790196218496.jpg',
        modelType: 'poulet_braise' as const,
        description: 'Poulet local fermier mariné 24h aux épices gboma et gingembre frais, grillé au feu de bois avec alloco doré et piment vert écrasé.',
        ingredients: ['Poulet bicyclette', 'Alloco bananes mûres', 'Piment vert maison', 'Oignons caramélisés'],
        isPopular: true,
    },
    {
        id: 'dish_amiwo',
        name: 'Amiwo Rouge au Wagashi & Poulet',
        category: 'signature',
        price: 3800,
        currency: 'FCFA',
        rating: 4.8,
        reviewsCount: 98,
        prepTime: '15 min',
        image: '/images/wagashi_amiwo_1790196228866.jpg',
        modelType: 'igname_pile' as const,
        description: 'Pâte de maïs rouge parfumée au bouillon de poulet fermier, accompagnée de fromage Peulh Wagashi poêlé et sauce tomate pimentée.',
        ingredients: ['Farine de maïs fine', 'Fromage Peulh Wagashi', 'Coulis de tomates fraîches', 'Épices royales'],
        isPopular: true,
    },
    {
        id: 'dish_akara',
        name: 'Plateau Akara Croustillants & Sauces',
        category: 'street',
        price: 2200,
        currency: 'FCFA',
        rating: 4.9,
        reviewsCount: 86,
        prepTime: '10 min',
        image: '/images/akara_streetfood_1790196240482.jpg',
        modelType: 'alloco' as const,
        description: 'Beignets de haricots blancs soufflés et ultra-croustillants, servis avec sauce piquante oignon-tomate et kluiklui concassé.',
        ingredients: ['Haricots blancs bio', 'Sauce dja maison', 'Échalotes dorées', 'Piment doux'],
        isPopular: false,
    },
    {
        id: 'dish_poisson',
        name: 'Capitaine Braisé à la Braise d’Atacora',
        category: 'signature',
        price: 5500,
        currency: 'FCFA',
        rating: 5.0,
        reviewsCount: 114,
        prepTime: '25 min',
        image: '/images/resto_ambiance_1790196207320.jpg',
        modelType: 'poisson_grille' as const,
        description: 'Poisson frais du jour pêché au large de Grand-Popo, assaisonné aux herbes sauvages avec igname frite et sauce moyo.',
        ingredients: ['Capitaine entier frais', 'Frites d’igname blanche', 'Sauce moyo citronnée', 'Condiments traditionnels'],
        isPopular: true,
    },
];