export const featuredRestaurants = [
    {
        name: 'Chez Mama Bénin',
        neighborhood: 'Cadjehoun, Cotonou',
        specialty: 'Cuisine traditionnelle béninoise & grillades',
        rating: 4.9,
        reviews: 320,
        status: 'Ouvert en continu',
        tables: 18,
        slug: 'chez-mama-benin',
        image: '/images/resto_ambiance_1790196207320.jpg',
        badge: 'Le plus populaire',
    },
    {
        name: 'Le Jardin Fidjrossè',
        neighborhood: 'Bord de Mer, Fidjrossè Plage',
        specialty: 'Fruits de mer, poissons grillés & cocktails',
        rating: 4.8,
        reviews: 215,
        status: 'Ouvert · Service terrasse',
        tables: 24,
        slug: 'le-jardin-fidjrosse',
        image: '/images/poulet_braise_1790196218496.jpg',
        badge: 'Vue Océan',
    },
    {
        name: 'Délice Cotonou & Lounge',
        neighborhood: 'Haie Vive, Cotonou',
        specialty: 'Fusion africaine, burgers gourmets & mocktails',
        rating: 4.7,
        reviews: 180,
        status: 'Ouvert jusqu’à 02h00',
        tables: 15,
        slug: 'delice-cotonou',
        image: '/images/wagashi_amiwo_1790196228866.jpg',
        badge: 'Ambiance lounge',
    },
];