import { Category, Dish, Order, Restaurant, RestaurantTable, User } from "@/types";

export const STORAGE_KEYS = {
  RESTAURANTS: 'qresto_restaurants_v2',
  CATEGORIES: 'qresto_categories_v2',
  DISHES: 'qresto_dishes_v2',
  TABLES: 'qresto_tables_v2',
  ORDERS: 'qresto_orders_v2',
  USERS: 'qresto_users_v2',
  CURRENT_USER: 'qresto_current_user_v2',
};

// Seed Data for Benin & West African Restaurants
export const INITIAL_USERS: User[] = [
  {
    id: 'user_delice',
    email: 'delice@qresto.africa',
    password: 'password123',
    firstName: 'Delice',
    lastName: 'SPEED',
    phone: '+229 97 00 00 99',
    role: 'RESTAURANT_OWNER',
    restaurantId: 'rest_delice',
    createdAt: '2026-03-01T10:00:00.000Z',
  },
  {
    id: 'user_mama',
    email: 'owner@chezmama.bj',
    password: 'password123',
    firstName: 'Reine',
    lastName: 'Dossou',
    phone: '+229 97 00 11 22',
    role: 'RESTAURANT_OWNER',
    restaurantId: 'rest_mama',
    createdAt: '2026-01-10T10:00:00.000Z',
  },
  {
    id: 'user_jardin',
    email: 'contact@jardin-fidjrosse.bj',
    password: 'password123',
    firstName: 'Patrick',
    lastName: 'Ahouandjinou',
    phone: '+229 95 33 44 55',
    role: 'RESTAURANT_OWNER',
    restaurantId: 'rest_jardin',
    createdAt: '2026-02-01T12:00:00.000Z',
  },
  {
    id: 'user_admin',
    email: 'admin@qresto.africa',
    password: 'admin123',
    firstName: 'Super',
    lastName: 'Admin',
    phone: '+229 90 00 00 00',
    role: 'SUPER_ADMIN',
    createdAt: '2026-01-01T08:00:00.000Z',
  },
];

export const INITIAL_RESTAURANTS: Restaurant[] = [
  {
    id: 'rest_delice',
    name: 'Delice SPEED',
    slug: 'delice-speed',
    description: 'Restauration rapide & délices gourmands au Bénin. Burgers gourmets, poulet croustillant et spécialités express.',
    address: 'Carrefour Sainte Rita, Cotonou',
    city: 'Cotonou',
    phone: '+229 97 00 00 99',
    email: 'contact@delicespeed.bj',
    logo: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=300&q=80',
    coverImage: '/src/assets/images/resto_ambiance_1790196207320.jpg',
    openingHours: '10h00 - 23h00 (7j/7)',
    isOpen: true,
    currency: 'FCFA',
    deliveryFee: 1000,
    minOrder: 2000,
    rating: 4.9,
    reviewCount: 128,
    category: 'Fast Food & Grillades',
    ownerId: 'user_delice',
    subscriptionPlan: 'FREE',
    subscriptionExpiresAt: '2026-12-31T23:59:59.000Z',
    settings: {
      soundNotifications: true,
      emailNotifications: true,
      acceptDelivery: true,
      acceptDineIn: true,
      acceptPickup: true,
      tableOrderDirect: true,
      autoConfirmOrders: false,
      momoNumber: '+229 97 00 00 99',
      momoProvider: 'MTN',
    },
    createdAt: '2026-03-01T10:00:00.000Z',
  },
  {
    id: 'rest_mama',
    name: 'Chez Mama Bénin',
    slug: 'chez-mama-benin',
    description: 'Le temple de la cuisine authentique béninoise à Cotonou. Igname pilée, Amiwo traditionnel, sauces locales et viandes braisées au feu de bois.',
    address: 'Rue 340, Quartier Haie Vive',
    city: 'Cotonou',
    phone: '+229 97 00 11 22',
    email: 'contact@chezmama.bj',
    logo: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=300&q=80',
    coverImage: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=1200&q=80',
    openingHours: '11h30 - 23h00 (Tous les jours)',
    isOpen: true,
    currency: 'FCFA',
    deliveryFee: 1000,
    minOrder: 2500,
    rating: 4.9,
    reviewCount: 342,
    category: 'Cuisine Béninoise & Grillades',
    ownerId: 'user_mama',
    subscriptionPlan: 'PRO_8000',
    subscriptionExpiresAt: '2026-12-31T23:59:59.000Z',
    settings: {
      soundNotifications: true,
      emailNotifications: true,
      acceptDelivery: true,
      acceptDineIn: true,
      acceptPickup: true,
      tableOrderDirect: true,
      autoConfirmOrders: false,
      momoNumber: '+229 97 00 11 22',
      momoProvider: 'MTN',
    },
    createdAt: '2026-01-10T10:00:00.000Z',
  },
  {
    id: 'rest_jardin',
    name: 'Le Jardin Fidjrossè',
    slug: 'le-jardin-fidjrosse',
    description: 'Face à la brise marine de Fidjrossè Plage, profitez de nos poissons braisés entiers, capitaines frais, langoustines et cocktails artisanaux.',
    address: 'Boulevard de la Marina, Plage de Fidjrossè',
    city: 'Cotonou',
    phone: '+229 95 33 44 55',
    email: 'info@jardin-fidjrosse.bj',
    logo: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=300&q=80',
    coverImage: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
    openingHours: '12h00 - 01h00',
    isOpen: true,
    currency: 'FCFA',
    deliveryFee: 1200,
    minOrder: 3000,
    rating: 4.8,
    reviewCount: 218,
    category: 'Poissons & Grillades Marines',
    ownerId: 'user_jardin',
    subscriptionPlan: 'STARTER_5000',
    subscriptionExpiresAt: '2026-11-30T23:59:59.000Z',
    settings: {
      soundNotifications: true,
      emailNotifications: false,
      acceptDelivery: true,
      acceptDineIn: true,
      acceptPickup: true,
      tableOrderDirect: true,
      autoConfirmOrders: true,
      momoNumber: '+229 95 33 44 55',
      momoProvider: 'MOOV',
    },
    createdAt: '2026-02-01T12:00:00.000Z',
  },
  {
    id: 'rest_afroburger',
    name: 'AfroBurger Lounge',
    slug: 'afroburger-lounge',
    description: 'Street-food premium revisitée : burgers gastronomiques aux sauces kinkeliba, frites croustillantes d\'igname et jus naturels pressés à froid.',
    address: 'Avenue Jean-Paul II, Cadjèhoun',
    city: 'Cotonou',
    phone: '+229 96 88 99 00',
    email: 'hello@afroburger.bj',
    logo: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=300&q=80',
    coverImage: 'https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=1200&q=80',
    openingHours: '11h00 - 23h30',
    isOpen: true,
    currency: 'FCFA',
    deliveryFee: 800,
    minOrder: 2000,
    rating: 4.7,
    reviewCount: 185,
    category: 'Burgers & Street Food Africaine',
    ownerId: 'user_mama',
    subscriptionPlan: 'PRO_8000',
    settings: {
      soundNotifications: true,
      emailNotifications: true,
      acceptDelivery: true,
      acceptDineIn: true,
      acceptPickup: true,
      tableOrderDirect: true,
      autoConfirmOrders: false,
    },
    createdAt: '2026-02-15T14:00:00.000Z',
  },
  {
    id: 'rest_oueme',
    name: 'Saveurs de l\'Ouémé',
    slug: 'saveurs-oueme',
    description: 'Les délices de la capitale historique Porto-Novo : poissons séchés à la braise, kpanman croustillant, sauces traditionnelles et boissons locales.',
    address: 'Carrefour Cinquantenaire, Ouando',
    city: 'Porto-Novo',
    phone: '+229 94 12 34 56',
    email: 'contact@saveursoueme.bj',
    logo: 'https://images.unsplash.com/photo-1543007630-9710e4a00a20?auto=format&fit=crop&w=300&q=80',
    coverImage: 'https://images.unsplash.com/photo-1514933651103-005eec06c04b?auto=format&fit=crop&w=1200&q=80',
    openingHours: '10h00 - 22h00',
    isOpen: true,
    currency: 'FCFA',
    deliveryFee: 700,
    minOrder: 2000,
    rating: 4.9,
    reviewCount: 97,
    category: 'Tradition Béninoise & Terroir',
    ownerId: 'user_jardin',
    subscriptionPlan: 'FREE',
    settings: {
      soundNotifications: true,
      emailNotifications: false,
      acceptDelivery: true,
      acceptDineIn: true,
      acceptPickup: true,
      tableOrderDirect: true,
      autoConfirmOrders: false,
    },
    createdAt: '2026-03-01T09:00:00.000Z',
  },
];

export const INITIAL_CATEGORIES: Category[] = [
  // Chez Mama categories
  { id: 'cat_mama_1', restaurantId: 'rest_mama', name: 'Plats Traditionnels', order: 1, icon: 'bowl-rice', active: true },
  { id: 'cat_mama_2', restaurantId: 'rest_mama', name: 'Grillades au Feu de Bois', order: 2, icon: 'fire-flame-curved', active: true },
  { id: 'cat_mama_3', restaurantId: 'rest_mama', name: 'Accompagnements & Alloco', order: 3, icon: 'utensils', active: true },
  { id: 'cat_mama_4', restaurantId: 'rest_mama', name: 'Boissons Locales & Jus Frais', order: 4, icon: 'glass-water', active: true },

  // Le Jardin categories
  { id: 'cat_jardin_1', restaurantId: 'rest_jardin', name: 'Poissons & Crustacés', order: 1, icon: 'fish', active: true },
  { id: 'cat_jardin_2', restaurantId: 'rest_jardin', name: 'Brochettes & Viandes', order: 2, icon: 'drumstick-bite', active: true },
  { id: 'cat_jardin_3', restaurantId: 'rest_jardin', name: 'Cocktails Tropicaux', order: 3, icon: 'martini-glass-citrus', active: true },

  // AfroBurger categories
  { id: 'cat_burger_1', restaurantId: 'rest_afroburger', name: 'Burgers Signature', order: 1, icon: 'burger', active: true },
  { id: 'cat_burger_2', restaurantId: 'rest_afroburger', name: 'Frites & Sides', order: 2, icon: 'cookie', active: true },
  { id: 'cat_burger_3', restaurantId: 'rest_afroburger', name: 'Boissons & Shakes', order: 3, icon: 'mug-hot', active: true },
];

export const INITIAL_DISHES: Dish[] = [
  // Chez Mama dishes
  {
    id: 'dish_mama_1',
    restaurantId: 'rest_mama',
    categoryId: 'cat_mama_1',
    name: 'Igname Pilée royale (Télibo / Agoun) & Sauce Gombo',
    slug: 'igname-pilee-royale-sauce-gombo',
    description: 'Igname blanche pilée à la commande selon la tradition, accompagnée de notre sauce gombo fraîche cuisinée au poisson fumé et crabes de mer.',
    price: 3500,
    originalPrice: 4000,
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    preparationTimeMin: 20,
    allergens: ['Poissons', 'Crustacés'],
    isPopular: true,
    isChefSpecial: true,
    has3DModel: true,
    model3DType: 'igname_pile',
    createdAt: '2026-01-10T10:00:00.000Z',
  },
  {
    id: 'dish_mama_2',
    restaurantId: 'rest_mama',
    categoryId: 'cat_mama_2',
    name: 'Poulet Bicyclette Braisé Fermier',
    slug: 'poulet-bicyclette-braise-fermier',
    description: 'Poulet local béninois mariné aux épices du terroir (gingembre, ail, poivre noir de Penja), grillé lentement à la braise de charbon de bois.',
    price: 4500,
    originalPrice: 5000,
    image: 'https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    preparationTimeMin: 25,
    allergens: [],
    isPopular: true,
    has3DModel: true,
    model3DType: 'poulet_braise',
    createdAt: '2026-01-10T10:00:00.000Z',
  },
  {
    id: 'dish_mama_3',
    restaurantId: 'rest_mama',
    categoryId: 'cat_mama_1',
    name: 'Amiwo rouge au Poulet doré & Piment vert',
    slug: 'amiwo-rouge-au-poulet-dore',
    description: 'Pâte de maïs rouge raffinée cuite dans un bouillon de poulet assaisonné, servie avec cuisse de poulet dorée et piment vert écrasé.',
    price: 3000,
    image: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    preparationTimeMin: 15,
    allergens: [],
    isPopular: true,
    has3DModel: false,
    createdAt: '2026-01-10T10:00:00.000Z',
  },
  {
    id: 'dish_mama_4',
    restaurantId: 'rest_mama',
    categoryId: 'cat_mama_3',
    name: 'Alloco doré croustillant au piment doux',
    slug: 'alloco-dore-croustillant',
    description: 'Bananes plantains mûres frites à point, dorées et fondantes, servies avec notre concassé de tomates et oignons frits.',
    price: 1500,
    image: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    preparationTimeMin: 10,
    allergens: [],
    has3DModel: true,
    model3DType: 'alloco',
    createdAt: '2026-01-10T10:00:00.000Z',
  },
  {
    id: 'dish_mama_5',
    restaurantId: 'rest_mama',
    categoryId: 'cat_mama_4',
    name: 'Bissap Rouge infusé à la Menthe & Gingembre (1L)',
    slug: 'bissap-rouge-menthe-gingembre',
    description: 'Infusion fraîche de fleurs d\'hibiscus sauvage du Bénin, relevée d\'une touche de gingembre frais et de menthe de notre potager.',
    price: 1200,
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    preparationTimeMin: 5,
    allergens: [],
    has3DModel: false,
    createdAt: '2026-01-10T10:00:00.000Z',
  },

  // Le Jardin dishes
  {
    id: 'dish_jardin_1',
    restaurantId: 'rest_jardin',
    categoryId: 'cat_jardin_1',
    name: 'Capitaine Braisé entier de l\'Océan (1.2 kg)',
    slug: 'capitaine-braise-entier-ocean',
    description: 'Pêché le matin même au large de Cotonou, mariné aux herbes côtières, cuit à la braise et servi avec alloco, attiéké et sauce moyo.',
    price: 8500,
    originalPrice: 9500,
    image: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    preparationTimeMin: 35,
    allergens: ['Poissons'],
    isPopular: true,
    isChefSpecial: true,
    has3DModel: true,
    model3DType: 'poisson_grille',
    createdAt: '2026-02-01T12:00:00.000Z',
  },
  {
    id: 'dish_jardin_2',
    restaurantId: 'rest_jardin',
    categoryId: 'cat_jardin_2',
    name: 'Brochettes Géantes de Bœuf Suya (4 pièces)',
    slug: 'brochettes-geantes-boeuf-suya',
    description: 'Fines lamelles de bœuf tendre enrobées d\'épices yaji / kankan traditionnelles, oignons rouges émincés et piment séché.',
    price: 3500,
    image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    preparationTimeMin: 15,
    allergens: ['Arachides'],
    isPopular: true,
    has3DModel: false,
    createdAt: '2026-02-01T12:00:00.000Z',
  },

  // AfroBurger dishes
  {
    id: 'dish_burger_1',
    restaurantId: 'rest_afroburger',
    categoryId: 'cat_burger_1',
    name: 'Le Dahomey Double Beef & Fromage Peulh',
    slug: 'le-dahomey-double-beef-fromage-peulh',
    description: 'Double steak de bœuf haché maison, fromage peulh (wagashi) grillé fondant, confit d\'oignons au miel de Savè, sauce burger maison.',
    price: 4500,
    originalPrice: 5000,
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    preparationTimeMin: 15,
    allergens: ['Lactose', 'Gluten'],
    isPopular: true,
    isChefSpecial: true,
    has3DModel: true,
    model3DType: 'burger',
    createdAt: '2026-02-15T14:00:00.000Z',
  },
];

export const INITIAL_TABLES: RestaurantTable[] = [
  // Chez Mama Tables
  { id: 'tab_mama_1', restaurantId: 'rest_mama', number: 1, name: 'Table VIP Terrasse', capacity: 4, active: true, createdAt: '2026-01-10T10:00:00.000Z' },
  { id: 'tab_mama_2', restaurantId: 'rest_mama', number: 2, name: 'Table Jardin 2', capacity: 2, active: true, createdAt: '2026-01-10T10:00:00.000Z' },
  { id: 'tab_mama_3', restaurantId: 'rest_mama', number: 3, name: 'Table Famille 3', capacity: 6, active: true, createdAt: '2026-01-10T10:00:00.000Z' },
  { id: 'tab_mama_4', restaurantId: 'rest_mama', number: 4, name: 'Table Pergola 4', capacity: 4, active: true, createdAt: '2026-01-10T10:00:00.000Z' },
  { id: 'tab_mama_5', restaurantId: 'rest_mama', number: 5, name: 'Table Intérieure 5', capacity: 2, active: true, createdAt: '2026-01-10T10:00:00.000Z' },

  // Le Jardin Tables
  { id: 'tab_jardin_1', restaurantId: 'rest_jardin', number: 1, name: 'Table Vue Mer 1', capacity: 4, active: true, createdAt: '2026-02-01T12:00:00.000Z' },
  { id: 'tab_jardin_2', restaurantId: 'rest_jardin', number: 2, name: 'Table Paillote 2', capacity: 6, active: true, createdAt: '2026-02-01T12:00:00.000Z' },
  { id: 'tab_jardin_3', restaurantId: 'rest_jardin', number: 3, name: 'Table Lounge 3', capacity: 2, active: true, createdAt: '2026-02-01T12:00:00.000Z' },
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ord_101',
    trackingCode: 'QR-7842',
    restaurantId: 'rest_mama',
    restaurantName: 'Chez Mama Bénin',
    restaurantPhone: '+229 97 00 11 22',
    type: 'DINE_IN',
    tableNumber: 4,
    items: [
      {
        dishId: 'dish_mama_1',
        name: 'Igname Pilée royale & Sauce Gombo',
        price: 3500,
        quantity: 2,
        notes: 'Piment bien relevé SVP',
      },
      {
        dishId: 'dish_mama_5',
        name: 'Bissap Rouge infusé à la Menthe (1L)',
        price: 1200,
        quantity: 1,
      },
    ],
    subtotal: 8200,
    deliveryFee: 0,
    total: 8200,
    status: 'PREPARING',
    customerName: 'Kofi Mensah',
    customerPhone: '+229 97 45 67 89',
    paymentMethod: 'MTN_MOMO',
    paymentStatus: 'PAID',
    createdAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    statusHistory: [
      { status: 'NEW', timestamp: new Date(Date.now() - 15 * 60 * 1000).toISOString(), note: 'Commande reçue depuis la Table 4' },
      { status: 'CONFIRMED', timestamp: new Date(Date.now() - 12 * 60 * 1000).toISOString(), note: 'Confirmée par la cuisine' },
      { status: 'PREPARING', timestamp: new Date(Date.now() - 5 * 60 * 1000).toISOString(), note: 'En cours de préparation au feu' },
    ],
  },
  {
    id: 'ord_102',
    trackingCode: 'QR-9310',
    restaurantId: 'rest_mama',
    restaurantName: 'Chez Mama Bénin',
    restaurantPhone: '+229 97 00 11 22',
    type: 'DELIVERY',
    items: [
      {
        dishId: 'dish_mama_2',
        name: 'Poulet Bicyclette Braisé Fermier',
        price: 4500,
        quantity: 1,
      },
      {
        dishId: 'dish_mama_4',
        name: 'Alloco doré croustillant',
        price: 1500,
        quantity: 1,
      },
    ],
    subtotal: 6000,
    deliveryFee: 1000,
    total: 7000,
    status: 'READY',
    customerName: 'Amina Alao',
    customerPhone: '+229 96 11 22 33',
    customerAddress: 'Cotonou, Haie Vive, Rue derrière ambassade de France',
    customerNotes: 'Sonner au portail marron',
    paymentMethod: 'CASH_ON_DELIVERY',
    paymentStatus: 'PENDING',
    createdAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
    statusHistory: [
      { status: 'NEW', timestamp: new Date(Date.now() - 30 * 60 * 1000).toISOString() },
      { status: 'CONFIRMED', timestamp: new Date(Date.now() - 28 * 60 * 1000).toISOString() },
      { status: 'PREPARING', timestamp: new Date(Date.now() - 20 * 60 * 1000).toISOString() },
      { status: 'READY', timestamp: new Date(Date.now() - 2 * 60 * 1000).toISOString(), note: 'Plat emballé et prêt à être remis au livreur' },
    ],
  },
  {
    id: 'ord_103',
    trackingCode: 'QR-2405',
    restaurantId: 'rest_jardin',
    restaurantName: 'Le Jardin Fidjrossè',
    restaurantPhone: '+229 95 33 44 55',
    type: 'DINE_IN',
    tableNumber: 1,
    items: [
      {
        dishId: 'dish_jardin_1',
        name: 'Capitaine Braisé entier de l\'Océan',
        price: 8500,
        quantity: 1,
      },
    ],
    subtotal: 8500,
    deliveryFee: 0,
    total: 8500,
    status: 'NEW',
    customerName: 'Édouard Houndété',
    customerPhone: '+229 94 88 77 66',
    paymentMethod: 'MOOV_MONEY',
    paymentStatus: 'PAID',
    createdAt: new Date(Date.now() - 4 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 4 * 60 * 1000).toISOString(),
    statusHistory: [
      { status: 'NEW', timestamp: new Date(Date.now() - 4 * 60 * 1000).toISOString(), note: 'Nouvelle commande Table 1' },
    ],
  },
];
